spring.application.name=Asset Manager

spring.data.mongodb.uri=${MONGODB_URI}

cloud.aws.credentials.access-key=${ACCESS_KEY}
cloud.aws.credentials.secret-key=${SECRET_KEY}
cloud.aws.region.static=${REGION}
cloud.aws.s3.bucket=${BUCKET_NAME}